### ISSUE TITLE
auto-delete approval when approved

### ISSUE THREAD

**Issue by emlinhax** [artscoop/django-approval#4]
is there a way to automatically delete an approval when it was approved?

OR

is there a way to only show the "This form is showing changes currently pending." warning if the approval has NOT been approved?
currently it shows even if the approval is approved because the code only checks IF there is an approval object but not if its approved or not.

suggested change:
monitored.py line 23:
```
if hasattr(obj, "approval") and obj.approval:
    if obj.approval.approved != True:                // added check
```

**Comment by artscoop** [comment]
Hi, and thanks for your ticket.
It's something I have not thought through enough, but I can have a look at this.
I'll have some time tomorrow morning to implement your change, I'll send an update when it's done

**Comment by emlinhax** [comment]
Hey mate,
whats the status?

**Comment by artscoop** [comment]
Hey,
You're lucky, I'm currently merging a pull request and...

**Comment by artscoop** [comment]
...it's done!!

**Comment by emlinhax** [comment]
Hey, the change is incorrect. The new if-statement leads to the else block if the model is approved.
And the else block shows an "ImproperlyConfigured" error.
The solution is to move the last check down into the if-statement.

Replace
```
if hasattr(obj, "approval") and obj.approval and not obj.approval.approved:
```
                
with

```
if hasattr(obj, "approval") and obj.approval: 
    if obj.approval.approved != True:
```
                
(like it was in my original solution provided in the first post in this issue)
