### ISSUE TITLE
A fix for the fix

### ISSUE THREAD

**Issue by emlinhax** [artscoop/django-approval#6]
I dont know if you got my other response in the old ticket since its closed so im making a new one just in case:

The change is incorrect. The new if-statement leads to the else block if the model is approved.
And the else block shows an "ImproperlyConfigured" error.
The solution is to move the last check down into the if-statement.

Replace
```
if hasattr(obj, "approval") and obj.approval and not obj.approval.approved:
```
                
with

```
if hasattr(obj, "approval") and obj.approval: 
    if obj.approval.approved != True:
```
                
(like it was in my original solution provided in the first post in this issue)

**Comment by emlinhax** [comment]
You broke the extension with your fix. You should try to patch that ASAP.
It will throw an ImproperlyConfigured error when a model is approved because if the misplaced if-check

**Comment by artscoop** [comment]
Hi, I just noticed your message. I rushed that thing and indeed, now it's obvious, I made this throw an exception by mistake...

**Comment by artscoop** [comment]
I'll just put the update of the object out of the condition. I'll only put the messaging under the `if` statement.

**Comment by artscoop** [comment]
So, I've spent a little more time and uploaded an update.
It adds a new boolean attribute to the sandbox model (see docs) to auto-delete approval info when approved.
Also, the message telling "this form is showing changes pending..." is only displayed when the approval is pending (it was also shown on denied changes).
Furthermore, when changes are denied, forms should not fetch the changes from the sandbox.

Tell me what you find if you can test it.

**Comment by emlinhax** [comment]
ValueError at /admin/mylibrary/book/add/ (example)
save() prohibited to prevent data loss due to unsaved related object 'source'.

when creating a new object that is monitored

./approval/listeners/monitored.py, line 33, in before_save

**Comment by artscoop** [comment]
I understand. Your model has a ForeignKey. I'll have to add that case to the scenario folder and work on that. Probably today.

**Comment by artscoop** [comment]
Fix attempted. I'll have to write automated tests but meanwhile, if you can tell me it works with the latest git version (`pip install https://github.com/artscoop/django-approval/archive/refs/heads/master.zip`)

**Comment by emlinhax** [comment]
Error when viewing approvals:

TemplateDoesNotExist at /admin/mylibrary/dynamicsandbox/
approval/display/sandbox-data.html

**Comment by artscoop** [comment]
Now this one is weird. I tried hard working with setuptools to include the template (a nightmare). It finally worked in december. Given you don't have the folder when installing the archive, it seems that only the wheel package is correct. Same build, different results... It's almost comical. Anyway, I'll try fiddling with pyproject.toml to find the issue.

**Comment by emlinhax** [comment]
Any progress?

**Comment by artscoop** [comment]
Yes, I ditched pyproject.toml (does not work well for packaging) in favor of the classic setup.py. It worked immediately, and both package versions (.tar.gz and .whl) seem to properly install the requested files (tried both in an empty venv). If you try installing again with `pip install https://github.com/artscoop/django-approval/archive/refs/heads/master.zip` tell me what you get

**Comment by emlinhax** [comment]
Same error (TemplateDoesNotExist "dynamicsandbox").

I did the following. I cloned the repo, ran the command you gave me (python 3.10 works, python 3.11 fails building).
Then I migrated the migrations in "scenario" and ran the server. 

Whenever I try to visit an approval model in the django-admin, I get that error.

I used your scenario project this time to make sure im not the one doing something wrong.

**Comment by artscoop** [comment]
Weird. I use Python 3.11. I'll have to test on another machine. And you're definitely not doing something wrong. That's the "it's working on my machine" syndrome, with something weird in the environment I'm working in. Note that I'm using Linux on both machines I code on.

**Comment by emlinhax** [comment]
Hey, any updates?

**Comment by artscoop** [comment]
Hi,
Still not sure since the scope of build tools is **HUGE** but I think I got it: https://stackoverflow.com/a/14159430/726230

I'll make a change right now and tell you when it's done.

**Comment by artscoop** [comment]
Ok, so try reinstalling with
`pip install -U --ignore-installed https://github.com/artscoop/django-approval/archive/refs/heads/master.zip`

then `pip freeze | grep approval` (on Linux) should say you have version 0.15.1.

Just tried on a clean venv, twice. Tell me what you get.

**Comment by emlinhax** [comment]
This seems to be working! No issues so far

**Comment by artscoop** [comment]
Excellent, thanks !
I'll prepare a new PyPI release then

**Comment by emlinhax** [comment]
Hey, is it released yet?

**Comment by emlinhax** [comment]
Ping

**Comment by artscoop** [comment]
Hi,
I just uploaded a new version on PyPI (0.15.1). I didn't have time yesterday because of work. If you test installing with `pip install -U django-approval`, is everything still working? (It will probably use the .whl version)

**Comment by emlinhax** [comment]
Works fine as far as I can tell! :+1:

**Comment by artscoop** [comment]
Thanks a lot!
